main: nl.lucasridder.minigames.Main
name: minigames
version: 1.1
author: LucasRidder
api-version: 1.15

commands:
  gamemode:
    aliases: gm
    usage: "Usage: /<command> [survival|creative|adventure|spectator|0|1|2|3] ([player])"
  survival:
    usage: "/<command>"
  lobby:
    aliases: hub
    usage: "/<command>"
  tntrun:
    aliases: tr
    usage: "/<command>"
  bedwars:
    aliases: bw
    usage: "/<command>"
  paintball:
    aliases: pb
    usage: "/<command>"
  kitpvp:
    usage: "/<command>"
  lock:
    aliases: lockdown
    usage: "/<command> (reden)"
  setspawn:
    usage: "/<command>"
  stop:
    usage: "/<command>"
  spawn:
    usage: "/<command>"
    aliases: leave
  fly:
    usage: "/<command> ([player])"